package:
  name: gfmix
  version: 1.0

source:
  git_url: https://github.com/TheBrownLab/gfmix.git

build:
  number: 4

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
  run:
    - r-quadprog=1.5_5
    - r-base=3.2.2
    - libiconv=1.16
    - readline=6.2

about:
    home: https://www.mathstat.dal.ca/~tsusko/doc/gfmix.pdf
    summary: Accelerated Estimation of Frequency Classes in Site-heterogeneous Profile Mixture Models
